hash-format = "sha256"

[[files]]
file = "mods/animatica.pw.toml"
hash = "e94fd2f80b6029f19fb0c68d5bbf443a21645af0d668c5a544e3b3f23508fb61"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2e1ad62031e3700de73a87957a4acca747436a4135da695705cb5d293aa0890"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d7651af3a8996488151254f0379fd7f1613edeaf7eac48bdeff447eeaf411965"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7eefb0f3d1b793f7dc57ee7cf368d055c9b1bf3556f61179f38f1c49c163c1bd"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "9c8b6d8e1a13a4f7edd081c1ab561c51069d6315a67c217a88fafcd1ddfb17a8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1ee56d5feb0ede9397b26f3c5b7543a3556088146d154b55172ef0e8b1a97705"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/hold-my-items.pw.toml"
hash = "e848d17092a61b91d0198361cc333fb5d3912cdb5bb561f0520f2f87a75db6e6"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "586dfaf9fcf001bb43e7ac4d546078a4dd504c3de6c3336520b6297864c6a650"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modefite-item-definition-backport.pw.toml"
hash = "2f7a3f4120d4c8a47f72c43cb105f1394f2898327fae75544c6e78b36d2aebf4"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "38aa99dcb8b2371b04716226723ab30b8954fcc80a503d20c12fc7fc519f26e9"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "421b6b05164e623dc65e0e4133fc484fb3b87b26b040ad4b2ffb239491d8bb2d"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "416b46fc5c69d7ca02932d2723c1240e6a6148b1dcca0e8e0be094ab6c156b5d"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "b7fbd8965f414bdff009887446e5c32cbc24f7d1ab9c64dcf6af4e227941d063"
metafile = true

[[files]]
file = "mods/pommel-held-item-models.pw.toml"
hash = "47893e0306684cf4d8e5ea25db8fd5ef5c90f5709effe02c7b5d1767ee67e703"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "b3a499bca7e44d15d7f3534e3776d59ff0b47d994e50313fda2b357de48f362c"
metafile = true

[[files]]
file = "resourcepacks/3d-bamboo-shoots.pw.toml"
hash = "91b79654153cbfb76554368f2d8db95298ffa5bdabed62b66f5505a65dbb99f8"
metafile = true

[[files]]
file = "resourcepacks/3d-crops.pw.toml"
hash = "82e610917524c6f1af58e102a1be333665ee9af1649477aae0546a30d1ae3114"
metafile = true

[[files]]
file = "resourcepacks/3d-dripstone.pw.toml"
hash = "a762028169b5b229e0b2f21d3d4c507855ee77081ca7d5a3af4c6c8a4513d33d"
metafile = true

[[files]]
file = "resourcepacks/3d-totem.pw.toml"
hash = "7f2ab93f9323166d45f965100776b81715a34bf11df3087df570c45a456e57af"
metafile = true

[[files]]
file = "resourcepacks/better-3d-beds.pw.toml"
hash = "3f24099e47ba95ef4f2a3b8557c300aba8868c3e16617db862ff47f9571bdef2"
metafile = true

[[files]]
file = "resourcepacks/better-lanterns.pw.toml"
hash = "120a936d5345b58a613ce793b0ce4bd6527aec7125eed4b6177f45d6e8602fb5"
metafile = true

[[files]]
file = "resourcepacks/better-leaves.pw.toml"
hash = "f23b343e4a4555895e697c5ce98971809056a721e4732e25ea5b6952d91c0180"
metafile = true

[[files]]
file = "resourcepacks/blinking-ender-eyes.pw.toml"
hash = "4963c119327192e1df1405aa0d77aa7cd95aec354f785506f1e4cf11dd5c646a"
metafile = true

[[files]]
file = "resourcepacks/blockier-goat-horn.pw.toml"
hash = "c37e5e523342078805bf8810632802af12670b8d25d4f835373953cbc7222feb"
metafile = true

[[files]]
file = "resourcepacks/door-tweaks.pw.toml"
hash = "bb1a9dace8267ee4bdc91360f3828de37fe03f4a3d9f2bce03ed418c8afa4852"
metafile = true

[[files]]
file = "resourcepacks/dramatic-skys.pw.toml"
hash = "bca8d231761e7e9935ae2cfe46fafc4d931dd50127869cd0f925fd2446e7e0f5"
metafile = true

[[files]]
file = "resourcepacks/effect-icon-plus.pw.toml"
hash = "75c9a54bfb7af90cf67c27e0a3a08f4c6cdfb39f33ef08fff7589120f1d97556"
metafile = true

[[files]]
file = "resourcepacks/enchant-icons-countxd.pw.toml"
hash = "d9e7e86ddb96102cedc1173006459c1cb4338698087bf16258abb23dd7889219"
metafile = true

[[files]]
file = "resourcepacks/enchanting-table-magic-circle.pw.toml"
hash = "bda8578a3cfb4686032c99f92a86d5eddfea2127e0066d300173861818f59847"
metafile = true

[[files]]
file = "resourcepacks/enchantment-glows.pw.toml"
hash = "0d276ab5bea474714acb436477b8d2340d7a5aa49d7930a5ad79f4de776e0bf8"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "c787950c5bdbff78bc2ef218554f1486fc81f747d7abd4a29fba5286229b225a"
metafile = true

[[files]]
file = "resourcepacks/extended-illumina-(not-enough-animations).pw.toml"
hash = "ca4aec8a1eb73c9e0a11db4abb8d9fc2ffc3f5dbf4926888a6ea550f34e357a0"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "b6643cac68927881baa84fa7f348a2d60b6d2f901b4612c7a8c4ad882f90f23b"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "d3571c12bae3b4ff244307f5f5bdfa1654175981eeda8d76059266eaa7d926fa"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "64f90fd9619a092a8a5493d6ad9605bc5fec13f50f02feef1dcf47c9496a80bd"
metafile = true

[[files]]
file = "resourcepacks/fresh-flower-pots-rotated.pw.toml"
hash = "c9ed097f96c53c48dd424083fac6a17d442670133e23d9c1b624851a642bd879"
metafile = true

[[files]]
file = "resourcepacks/fresh-flower-pots.pw.toml"
hash = "5e3dc385b2158a5d7c83d256f79b5b497690e154b03bc3c58de283bf695e4e88"
metafile = true

[[files]]
file = "resourcepacks/fresh-food.pw.toml"
hash = "83f86fc2cc7ccbdec969086f79b842e6df934948ad498bccc2e5940b4f26324e"
metafile = true

[[files]]
file = "resourcepacks/just-fancy-torches.pw.toml"
hash = "62640decdfff74b74a123d527909ac9549a3258a4a9d31c51f829699fc6f4a36"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "98520d370f14406836b850e9ca58debe0b5e25475279d7f2a46b1c3151b222a8"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/os-3d-iron-bars.pw.toml"
hash = "9a0dd881ae4f46c8fd877f23c8fcb89f231dcd7d8874f75b2757cfa0a802f472"
metafile = true

[[files]]
file = "resourcepacks/particles-updated.pw.toml"
hash = "c8af18f6c410237b5d6e34b94cdad8f36fdb7d6584cbca4ac0e258c53e288fbe"
metafile = true

[[files]]
file = "resourcepacks/patos-3d-brews.pw.toml"
hash = "fd019b45bb860f4abdbbcce4242fe654669e2e91657f85b47ab47dea21016723"
metafile = true

[[files]]
file = "resourcepacks/rays-3d-ladders.pw.toml"
hash = "b2f202f7437e122b0f62038fd99ac93898d7d36623ca3e7a1ec513c72623b071"
metafile = true

[[files]]
file = "resourcepacks/rays-3d-rails.pw.toml"
hash = "0e80f97855da0ee8b2cba02d4cc1f3c82f50bd1ec0772645cfd5dd5d6f4e9a86"
metafile = true

[[files]]
file = "resourcepacks/simple-3d-chain.pw.toml"
hash = "885359a3e81c3ec954a2770fa55df60d37db4fd248b0d6c73a7d3cf564fe104b"
metafile = true

[[files]]
file = "resourcepacks/simple-grass-flowers.pw.toml"
hash = "bc4dcbd6b77adb2180049d63ed4a8981553f06dbf3e32080022ffd87dd1fb09b"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "32fe0fe8941110f8fba07ce7768faa1797de6b28e961ab65b483c380fc0a365a"
metafile = true

[[files]]
file = "resourcepacks/unique-dark.pw.toml"
hash = "cd44bb07e7b0d4bb87b8428933787d9c7a689740b94e185da3ebb9ea26e61db5"
metafile = true

[[files]]
file = "resourcepacks/visual-armor-trims.pw.toml"
hash = "e7a3945feb4ef231579385cb92d1298a06fd7af4655d11763e563ee06980d642"
metafile = true

[[files]]
file = "resourcepacks/vvi.pw.toml"
hash = "c27d7f15e62850450221bfc629f00fb2fd5b8247d0684d05b77c1daa7bbcf1a9"
metafile = true
