hash-format = "sha256"

[[files]]
file = "mods/advanced-loot-info.pw.toml"
hash = "bd5d30664fd28936f6c13186caebc45826d12f8688a41145d08ccc7ed4771a94"
metafile = true

[[files]]
file = "mods/anvians-lib.pw.toml"
hash = "245c701a5f92bdf43202e9aa39e001b75cc8cc9a773916ddbe7bacb0b59c800e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "f3f98ccb142504aa558f3250b5a9bcda5d9fb45634562a4b7f886489575f6f5a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "30eff8901d5955ab62196e335926047f6c00278fd95eb04b4e4b7122a8c31f15"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a1e024094c28068c99a6da1c5867cbd4e66a315718039659bfa533a138762d9e"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "d6878871a07870b33821beed20118368e779c17574062d5d771eb38b9403e875"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b5feeae74fe992084ec5cb12eab3404ddd5054e85c9006f7ba4d65f209de13f"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "0cc9069aeee558e036c7afd064d37d9f468ea1138705da0fe4aad64d95312f79"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "ec2c437fe50a3f8ea6077215974ba9f769cb94eb29432156cbbe43137a74013f"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1173755b093b4f9a8aca00520d87bc35178fe19c54e59debe5c48d0c9063b91c"
metafile = true

[[files]]
file = "mods/chat-tools.pw.toml"
hash = "b00d2704438ff81689d0c6501dae1f7345b5306bed4a97b638ac6e4df04b2384"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "ade96e54f3cc61a9a64356f522f8527f15a20518fe9a782229af7423358fc017"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/craftify.pw.toml"
hash = "800fa9bd83d47d78dddd57854d8ca95fe4b71a0a1cfdf6996544e1e6591d9470"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "b079b010767e7589c98ee4c6281eec59cda6cf2b8ca83c75aaa478af7253b6bf"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "10742d60f7069f58268b846ab1661842cc7613e8c6d96c03c341b8668a4ffc1e"
metafile = true

[[files]]
file = "mods/custom-crosshair-mod.pw.toml"
hash = "fc0c7f60edc731c50323e7d3bf4569eb650ccc3c4aec8d862b6b01d16e8d8a92"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
hash = "62fefdf6c40874fea0304161568f86cfcaa3efb8b6b5788010151f3778c22e77"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "a763f10ac9de0fbdc4efaf6a998996c54213931cd9a393129f1ff3231fdf8cf9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1ee56d5feb0ede9397b26f3c5b7543a3556088146d154b55172ef0e8b1a97705"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/forge-config-screens.pw.toml"
hash = "ca2cad39790a1ab7dca3dc22d8becc6d148c711fb39f3ababf97d0936a886984"
metafile = true

[[files]]
file = "mods/horse-expert.pw.toml"
hash = "58f60f9444dd9e26a359e461d8f03662625d6726c6183398428fc3a5062f8dc1"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "f669b069214a8e88d17066ff6715fe131568cd190450ba408b4c2c5479a1a263"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "cc5ce2c69f275f245fccbb9f673f5b6711175034bdf41f48cfb672e652ea984b"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "e9a8feb043bb0071198f4170d6484f30a6465ed73b2f2083549642e2ce7c4707"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "80264d11a93ffb63f1592be06f8dcdf276bc5a6d2b666dfa9a5d2d10dfb29282"
metafile = true

[[files]]
file = "mods/itemlocks.pw.toml"
hash = "576bb0b02615b8dc66b1e8a285180ebf4e8394ce45707e8a72370bcaf3e2e4ff"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f644c401c3ef437f661564171abc8be8f13ad71cb67461734ab402d2ebe7cc47"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "ac7a23bef8a66288e60bb8767df21b76f41b672e8f762ed1aef1f93876eb8689"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "60300c6873d127b49ba31b11abc8fa7ac65008480c21c0db4c36d46db25426c5"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "28e1e39df852ca1db18840a224c8cd09cb51f439cf26db3f704204bb9e8db3e5"
metafile = true

[[files]]
file = "mods/leave-my-bars-alone.pw.toml"
hash = "a17afc44cdee8e7873e9fa6c33c666998b4d4c89581ff53d3ebcb718a143f45f"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "cc298019c2d3a47a97e72363b942fe408e5ecb7ff476fe08155793f2f1578317"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "586dfaf9fcf001bb43e7ac4d546078a4dd504c3de6c3336520b6297864c6a650"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "6bfb82960a27af2c360036e01c0131c3ad9c778b4ba5e3df51bafe4f175317db"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/morebeeinfo.pw.toml"
hash = "d1ffaba2c3526a5d5cb21d758ab8ded09c648d810bbe7949ef6167b00783107c"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "3dc86c0b4d31199f6f8579b8460686201ce8b9c87e1be5afaf50be9995add1e0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/notes.pw.toml"
hash = "3de765a444586708b33aa1cbe2c377833681127068b86b22c8918affa3e86ee5"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "1f7e880bc7596c4cca8334031e8e6974a37f723086e941454b40dd86114739d0"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "b3a499bca7e44d15d7f3534e3776d59ff0b47d994e50313fda2b357de48f362c"
metafile = true

[[files]]
file = "mods/screenshot-viewer.pw.toml"
hash = "7e64d3e87b78d072f992941580a2dddfc4684a7143371a5e394bc42452160441"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "2e6fb1842744392bac79f92c25c04613af1b82a904a29f7afd0df4f61a4c757e"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "3159f65be74fdf8c382f2079d9db965972c8612e661f126be522ae37a73c34f8"
metafile = true

[[files]]
file = "mods/simple-armor-hud.pw.toml"
hash = "e9ab2f11a9bc247eb4062fe2c9a91e3aea1e939de001e46cae75faaedcba9107"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "f985288dc5af3c5fde96f303509839f1836c2a9716c321eb7910b90563413aa3"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "e0047e26d3d4a5a290dc150e9a7c5c5f64cde9e6a0538eaa6f6060374349700f"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "554cf9b66823e7681394b23933e3d1659b6e7ae35cdc7721e402a762d7e332c6"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "df71b5d7427e9a508e9f298b5cdec84aa8c4fcb584beb0d16d86efb9d47b3bcd"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "213860e0c0161f60fba897f526d92ca703208dd26b636e6eaadb2c715d8a2f58"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d33719fa79b683a327acafbe1e2617482b5a3272fd471bb822a72314d3cd511f"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "31938394e90226cd1529b7be0283394bf2eb7814a8e4f5488879bf75c6945ab8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "33500c6577b5a83808da55dac95cbe731bc771be2db59e4754d24a86cc15e6a8"
metafile = true
