name = "More Ez"
author = "break08"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "986c30cf499f6cded58828b5e4d7927c8fb80912346ed6d96239cfffb39caf03"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
