name = "Super Optimization Pack"
author = "break08"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1152f40c0a11e434e88ad36e4842ae4f3af6ca7d957cb7d5eeaaa9f60ea7fc6f"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
